//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunicationsShowroom.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoEmployees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InfoEmployees()
        {
            this.AccountEmployees = new HashSet<AccountEmployees>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateEnterOnJob { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> GoodsSold { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountEmployees> AccountEmployees { get; set; }
        public virtual Device Device { get; set; }
    }
}
